import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";

const pop = Poppins({
  subsets: ["latin"],
  variable: "--font-pop",
  weight: ["100", "200", "400", "500", "600", "700"],
});

// localStorage.theme = "light";
export const metadata: Metadata = {
  title: "Opinionest",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={pop.className}>{children}</body>
    </html>
  );
}
